# docker-compose.yaml

services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile

    container_name: link-graph-server

    ports:
      - "5001:5000" #HOST_PORT:CONTAINER_PORT

    environment:
      NODE_ENV: development

    volumes:
      - server_app:/app
      - server_node_modules:/app/node_modules

    command: pnpm dev

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile

    container_name: link-graph-client

    ports:
      - "3001:3000"

    environment:
      NODE_ENV: development

    volumes:
      - client_app:/app
      - client_node_modules:/app/node_modules
      - client_next:/app/.next

    command: pnpm dev

    depends_on:
      - server

  postgres:
    image: postgres:16
    container_name: link-graph-postgres
    environment:
      POSTGRES_DB: link_graph
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresPassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  server_app:
  server_node_modules:
  client_app:
  client_node_modules:
  client_next:
  postgres_data:
